### ISSUE TITLE
Crash with Brewin' and Chewin' kegs

### ISSUE THREAD

**Issue by Brown-bricks** [DragonsPlusMinecraft/CreateCentralKitchen#45]
### Minecraft Version

1.19.2

### What Mods Conflicts with

Brewin' And Chewin'

### Describe the Incompatibility

Certain recipes cause a crash which locks the user out of the world.

### Other Mods

All mods listed in the crash report. Relevant ones include Canary, Farmer's Delight, Italian Delight and Brewin' and Chewin'.

### Crash Report or Log

https://gist.github.com/Brown-bricks/88dda4ebfb3f6929b4315413ecaaf6f3

### Mod Version

0.5.0.i-1.3.5

### Forge Version

1.19-2.0

**Comment by MarbleGateKeeper** [comment]
```
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.minecraft.world.item.Item.m_41469_()" is null
	at umpaz.brewinandchewin.common.block.entity.KegBlockEntity.canFerment(KegBlockEntity.java:334) ~[BrewinAndChewin-1.19-2.0.jar%23462!/:1.19-2.0] {re:mixin,re:classloading,pl:mixin:APP:create_central_kitchen.mixins.json:common.brewinandchewin.KegBlockEntityMixin,pl:mixin:A}
	at umpaz.brewinandchewin.common.block.entity.KegBlockEntity.fermentingTick(KegBlockEntity.java:204) ~[BrewinAndChewin-1.19-2.0.jar%23462!/:1.19-2.0] {re:mixin,re:classloading,pl:mixin:APP:create_central_kitchen.mixins.json:common.brewinandchewin.KegBlockEntityMixin,pl:mixin:A}
```

**Comment by MarbleGateKeeper** [comment]
Ok, after carefully examing, I bilieve you should report it to Brewin' & Chewin' with details of what exactly key was brewing.
Central Kitchen adds no recipe or fluids or items to Brewin' & Chewin' and doesn't mess up its code of recipe or fermentng process.
