### ISSUE TITLE
placing sticky basket crashes game (1.19.2)

### ISSUE THREAD

**Issue by Gitcrafter** [DragonsPlusMinecraft/CreateCentralKitchen#86]
### Minecraft Version

1.19.2

### Describe the Bug

placing a sticky basket from Miner´s Delight crashes the game, only happens when Create Central Kitchen is loaded

relevant mods:
minecraft forge 1.19.2: 43.3.7
create forge 1.19.2: 0.5.1f
create central kitchen forge 1.19.2: 1.3.10
farmers delight forge 1.19.2: 1.2.3
miners delight forge 1.19.2: 1.1.2

crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 2024-03-29 16:06:27
Description: Unexpected error

java.lang.ClassCastException: class com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity cannot be cast to class vectorwing.farmersdelight.common.block.entity.BasketBlockEntity (com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity is in module miners_delight@1.19.2-1.1.2 of loader 'TRANSFORMER' @4eb9f2af; vectorwing.farmersdelight.common.block.entity.BasketBlockEntity is in module farmersdelight@1.19.2-1.2.3 of loader 'TRANSFORMER' @4eb9f2af)
	at com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity.<init>(StickyBasketBlockEntity.java:31) ~[miners_delight-1.19.2-1.1.2.jar%23158!/:1.19.2-1.1.2] {re:mixin,re:classloading,pl:mixin:A}
	at com.sammy.minersdelight.repack.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:139) ~[miners_delight-1.19.2-1.1.2.jar%23158!/:1.19.2-1.1.2] {re:classloading}
	at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:86) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:BlockEntityTypeMixin,pl:mixin:A}
	at com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlock.m_142194_(StickyBasketBlock.java:179) ~[miners_delight-1.19.2-1.1.2.jar%23158!/:1.19.2-1.1.2] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:255) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:158) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.7.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Miner's Delight (miners_delight), Version: 1.19.2-1.1.2
		at TRANSFORMER/miners_delight@1.19.2-1.1.2/com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity.<init>(StickyBasketBlockEntity.java:31)
Stacktrace:
	at com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity.<init>(StickyBasketBlockEntity.java:31) ~[miners_delight-1.19.2-1.1.2.jar%23158!/:1.19.2-1.1.2] {re:mixin,re:classloading,pl:mixin:A}
	at com.sammy.minersdelight.repack.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:139) ~[miners_delight-1.19.2-1.1.2.jar%23158!/:1.19.2-1.1.2] {re:classloading}
	at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:86) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:BlockEntityTypeMixin,pl:mixin:A}
	at com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlock.m_142194_(StickyBasketBlock.java:179) ~[miners_delight-1.19.2-1.1.2.jar%23158!/:1.19.2-1.1.2] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:255) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:158) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Eragon1997'/58, l='ClientLevel', x=-7.50, y=-60.00, z=-6.50]]
	Chunk stats: 729, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 293 game time, 293 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2280) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.7.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1966420160 bytes (1875 MiB) / 3422552064 bytes (3264 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card 0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card 0 deviceId: 0x15d8
	Graphics card 0 versionInfo: DriverVersion=26.20.14054.1001
	Graphics card 1 name: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
	Graphics card 1 vendor: NVIDIA (0x10de)
	Graphics card 1 VRAM (MB): 4095.00
	Graphics card 1 deviceId: 0x2191
	Graphics card 1 versionInfo: DriverVersion=31.0.15.4626
	Memory slot 0 capacity (MB): 8192.00
	Memory slot 0 clockSpeed (GHz): 2.67
	Memory slot 0 type: DDR4
	Memory slot 1 capacity (MB): 8192.00
	Memory slot 1 clockSpeed (GHz): 2.67
	Memory slot 1 type: DDR4
	Virtual memory max (MB): 26499.73
	Virtual memory used (MB): 14879.34
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 298.60
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.2-forge-43.3.7
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.26, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Eragon1997'/58, l='ServerLevel[New World]', x=-7.50, y=-60.00, z=-6.50]]
	Data Packs: vanilla, mod:farmersdelight, mod:mixinextras (incompatible), mod:miners_delight (incompatible), mod:forge, mod:flywheel (incompatible), mod:create, mod:create_central_kitchen, mod:create_dragon_lib, create_central_kitchen:farmersdelight, create_central_kitchen:miners_delight
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		miners_delight-1.19.2-1.1.2.jar                   |Miner's Delight               |miners_delight                |1.19.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.3.7-universal.jar                 |Forge                         |forge                         |43.3.7              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.19.2-0.6.10-20.jar               |Flywheel                      |flywheel                      |0.6.10-20           |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		create_central_kitchen-1.19.2-for-create-0.5.1.f-1|Create: Central Kitchen       |create_central_kitchen        |1.3.10              |DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.19.2-1.2.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.2.3               |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 8ad75c94-feb3-4377-be6b-3067c50b5cf6
	FML: 43.3
	Forge: net.minecraftforge:43.3.7

**Comment by MarbleGateKeeper** [comment]
Seems like I didn't cheery pick fix from 1.20.1 brance....Thanks for reporting.

--

I did, but I didn't cheery pick the fix here: https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/blob/c23f2bd098cab480c257e3e7a3ec46dde75fcc56/src/main/java/plus/dragons/createcentralkitchen/content/logistics/block/basket/SmartBasketBlockEntity.java#L19

Will fix later.

**Comment by Gitcrafter** [comment]
thanks for the quick reply

**Comment by Gitcrafter** [comment]
thank you
